### ISSUE TITLE
Nice Recipe

### ISSUE THREAD

**Issue by til-gaertner** [LoraArmstrong/forking-workflow-exercise#2]
A quick search led me to this recipe, what do you think about it: [Tacos al Pastor](https://www.thespruceeats.com/tacos-al-pastor-recipe-4172074)

**Comment by LoraArmstrong** [comment]
I think it looks delicious, although that much pork shoulder will be very expensive in the Netherlands...I think you should go ahead and add this recipe.

**Comment by til-gaertner** [comment]
I hope this works all like described :D
